### ISSUE TITLE
yacc error while making?

### ISSUE THREAD

**Issue by chenjinyuan87** [mynlp/enju#2]
Hello:
Could you tell me what's the problem?
When i trying making enju, it says: yacc is not found, so i installed byacc.
And then i found the following error:
make[2]: Entering directory `/home/tianji006/enju-master/ll/src'
/bin/bash ../ylwrap yacc.yy y.tab.c yacc.cc y.tab.h `echo yacc.cc | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output yacc.output -- yacc -d -v 
yacc: e - line 191 of "/home/tianji006/enju-master/ll/src/yacc.yy", syntax error
%param {void *parm}
^
make[2]: *** [yacc.cc] Error 1
make[2]: Leaving directory `/home/tianji006/enju-master/ll/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/tianji006/enju-master/ll'
make: *** [all-recursive] Error 1

Thank you.

**Comment by sumire-uematsu** [comment]
We found that necessary files for making enju were not on the repository.
At the desired state, you could have made enju without yacc.

We added the necessary files (such as yacc.{cc,hh} which are generated by running yacc)
to the master branch,
so now the branch would work for you.
