### ISSUE TITLE
yacc issue

### ISSUE THREAD

**Issue by kchro** [mynlp/enju#9]
I have been getting an error after doing 'make' on MacOS.

...
libtool: link: g++ -fstrict-aliasing -W -Wall -g -O2 -Wl,-rpath -Wl,/usr/local/lib -rdynamic -o lilfes lilfes-main.o -Wl,-bind_at_load  ./.libs/liblilfes.a -ldl -lbz2 -lz -lutil -lcurses -lreadline
make[2]: *** No rule to make target `yacc.h', needed by `yacc.hh'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by miyao-yusuke** [comment]
have you tried the latest version in `master`?  this error should not happen, because `yacc.hh` is included in the repository and the rule to create `yacc.hh` from `yacc.h` is removed.

**Comment by rbossy** [comment]
Hi, I have the same issue compiling from the latest commit in the master branch (30841479e2bffcda5d021e1b9860836892b45640)

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
```

I'm on Ubuntu 16.04

**Comment by miyao-yusuke** [comment]
I'm not really sure why this happens (this error does not appear in my environment under Ubuntu 16.04 LTS), but as s short term solution, `yacc.h` is added to the `develop` branch (it is just a copy of `yacc.hh`).

Can you try the latest code on `develop`?  I'll merge it to `master` if it works.

**Comment by rbossy** [comment]
It did compile, I will try to run it later today.

Thanks a lot.

**Comment by miyao-yusuke** [comment]
this is merged to `master` (as well as other fixes).
